Add cfg flag
Need to build m rustdoc.

error: requires --cfg zerocopy_derive_union_into_bytes;
https://github.com/google/zerocopy/discussions/1802
--> external/crosvm/devices/src/virtio/snd/layout.rs:341:34
|
341 | #[derive(Copy, Clone, Immutable, IntoBytes, FromBytes, KnownLayout)]
|
Bug:b/492233402
Test: m rustdoc
Change-Id: Icb6b2e260a7688e7f297a71f4f7b32daec763a5a